In [1]:
import numpy
from matplotlib import pyplot
%matplotlib inline

In [2]:
L=1.0
nx=51
dx=L/(nx-1)
alpha=1.22e-3
q=0.0

x=numpy.linspace(0.0, L, num=nx)

T0=numpy.zeros_like(x) #get the length from another array
T0[0]=100.0

In [3]:
from scipy import linalg

In [4]:
def lhs_operator(nx,sigma):
    D=numpy.diag((2 + 1/sigma) * numpy.ones(nx-2))
    D[-1,-1]=1+1/sigma
    U=numpy.diag(-1.0*numpy.ones(nx-3),k=1) 
    #here the k determines where in the matrix the diagonal will be. K=0 will give normal diagonal
    L=numpy.diag(-1.0*numpy.ones(nx-3),k=-1)
    #A=D+U+L
    A=D+U+L
    
    return A

In [5]:
print(lhs_operator(7,1.0))

[[ 3. -1.  0.  0.  0.]
 [-1.  3. -1.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  0. -1.  3. -1.]
 [ 0.  0.  0. -1.  2.]]


In [6]:
D=numpy.diag(2.0 * numpy.ones(5))
#print(D)
D[1,2]=4.0
print(D)
D=numpy.diag(2.0 * numpy.ones(4), k=1)
print(D)

[[2. 0. 0. 0. 0.]
 [0. 2. 4. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]
[[0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0.]]


In [7]:
def rhs_vector(T,sigma,q,dx):
    b=T[1:-1]/sigma
    b[0]+=T[0]
    b[-1]+=q*dx
    
    return b

In [8]:
def btcs(T0,nt,dt,dx,alpha,q):
    sigma=alpha*dt/dx**2
    A=lhs_operator(nx,sigma)
    T=T0.copy()
    for n in range (nt):
        b=rhs_vector(T,sigma,q,dx)
        T[1:-1]=linalg.solve(A,b)
        T[-1]=T[-2]+q*dx
        
    return T

In [ ]:
nt=1000
sigma=0.5
dt=sigma*dx**2/alpha
T3=btcs(T0,nt,dt,dx,alpha,q)
pyplot.plot(x,T3)